version: '3.5'

services:
  # nginx:
  #   image: nginx:1.15.10-alpine
  #   container_name: "app_nginx"
  #   ports:
  #     - 80:80
  #     - 443:443
  #   restart: unless-stopped
  #   depends_on:
  #     - app
  #   volumes:
  #     - ../:/var/www/cpa:ro
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #   networks:
  #     - cpa_system

  app:
    build: ./
    container_name: "app"
    depends_on:
      - mariadb
    volumes:
      - ./data/uploads:/app/uploads
      - ./kcms/appsettings.production.json:/app/appsettings.json
    networks:
      - kcms_system
    ports:
      - 8090:80
    environment:
      # DB_HOST: mariadb
      # DB_PORT: 3306
      # DB_DATABASE: ${MYSQL_DATABASE}
      # DB_USERNAME: ${MYSQL_USER}
      # DB_PASSWORD: ${MYSQL_PASSWORD}
      ASPNETCORE_ENVIRONMENT: Development

  adminer:
    image: adminer
    container_name: "kcms_adminer"
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - mariadb
    networks:
      - kcms_system

  mariadb:
    image: mariadb:10.5.9
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # ports:
      # <Port exposed> : < MySQL Port running inside container>
      # - '3306:3306'
    # expose:
      # Opens port 3306 on the container
      # - '3306'
      # Where our data will be persisted
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - kcms_system

networks:
  kcms_system:
    driver: bridge
